---
title: "RGUI"
author: "Tomas Barriga"
date: "10/14/2021"
output: html_document
---

```{r setup, include=FALSE}
# INSTALL AND LOAD PACKAGES ################################

# Install pacman ("package manager") if needed
if (!require("pacman")) install.packages("pacman")
# pacman must already be installed; then load contributed
# packages (including pacman) with pacman
pacman::p_load(magrittr, pacman, tidyverse, readxl, sf, reticulate)

source("R/RGUI_CrashPrep.R")
source("R/RGUI_RoadwayPrep.R")
source("R/RGUI_Functions.R")
```

# CRASH DATA

```{r Load Crash Data}
location <- read_csv("data/Crash_Data_14-20.csv",show_col_types = F)
vehicle <- read_csv("data/Vehicle_Data_14-20.csv",show_col_types = F)
rollups <- read_csv("data/Rollups_14-20.csv",show_col_types = F)
```

```{r Check Crash Data Headers}
location <- check_location(location)
vehicle <- check_vehicle(vehicle)
rollups <- check_rollups(rollups)
```

```{r Join Crash Data}
crash <- left_join(location,rollups,by='crash_id')
crash <- left_join(crash,vehicle,by='crash_id')
rm("location","vehicle","rollups")
# crash <- filter_CAMS(crash)
```

```{r}
# write.csv(crash, "C:/Users/barrigat/Downloads/crashtest2.csv",row.names = F)
```

# Roadway Data

```{r Load Roadway Data}
# load AADT csv
aadt <- read_csv("data/AADT_Rounded.csv",show_col_types = F)
# load functional class csv
functional_class <- read_csv("data/Functional_Class_ALRS.csv",show_col_types = F)
# load intersections csv and convert to spatial frame
intersections <- read_csv("data/Intersection_w_ID_MEV_MP.csv") %>%
  st_as_sf(
    coords = c("BEG_LONG", "BEG_LAT"), 
    crs = 4326,
    remove = F) %>%
  st_transform(crs = 26912)
# load UTA stops shapefile
UTA_stops <- read_sf("data/UTA_Stops/UTA_Stops_and_Most_Recent_Ridership.shp") %>%
  st_transform(crs = 26912) %>%
  select(UTA_StopID) %>%
  st_buffer(dist = 304.8) #buffer 1000 ft (units converted to meters)
# load schools (not college) shapefile
schools <- read_sf("data/Utah_Schools_PreK_to_12/Utah_Schools_PreK_to_12.shp") %>%
  st_transform(crs = 26912) %>%
  select(SchoolID) %>%
  st_buffer(dist = 304.8) #buffer 1000 ft (units converted to meters)
# modify intersections to include bus stops and schools nearby
intersections <- mod_intersections(intersections,UTA_Stops,schools)
# remove unneeded dfs
rm("schools","UTA_stops")
# load lanes csv
lanes <- read_csv("data/Lanes.csv",show_col_types = F)
# load pavement messages csv
pavement_messages <- read_csv("data/Pavement_Messages.csv",show_col_types = F)
# load speed limit csv
speed_limit <- read_csv("data/UDOT_Speed_Limits_2019.csv",show_col_types = F)

# urban_code_large <- read_sf("data/Urban_Boundaries_Large.shp")
# urban_code_small <- read_sf("data/Urban_Boundaries_Small.shp")

# urban_code_test <- shapefile("data/Urban_Boundaries_Large")
```

```{r Check Roadway Data Headers}
aadt <- check_aadt(aadt)
functional_class <- check_functionalclass(functional_class)
intersections <- check_intersections(intersections)
lanes <- check_lanes(lanes)
pavement_messages <- check_pavementmessages(pavement_messages)
speed_limit <- check_speedlimit(speed_limit)
```

```{r Join Roadway Data}
road <- left_join(,,by='')
road <- left_join(,,by='')
road <- left_join(,,by='')
road <- left_join(,,by='')
road <- left_join(road,,by='')
rm("aadt","functional_class","intersections","lanes","pavement_messages","speed_limit")
```

```{r Temporary Load Excel GUI Data}
# The code before this should hopefully get us to this point. In the meanwhile,
# we can just use the file created by the Excel GUI and modify it as needed.
CAMS_no_spatial <- read_csv("data/CAMSinput.csv")
ISAM <- read_csv("data/UICPMinput.csv")

# CAMS from the Excel GUI doesn't include spatial data so we can add it in here.
# load sf data
sf <- read_sf("data/UDOT_Routes_(ALRS)/UDOT_Routes_(ALRS).shp") %>%
  select(ROUTE_ALIA, BEG_MILEAG, END_MILEAG, SHAPE_Leng)
# append spatial data
CAMS <- right_join(sf, CAMS_no_spatial, by = c("ROUTE_ALIA"="LABEL"), keep = TRUE) %>%
  select(-ROUTE_ALIA) %>%
  st_transform(crs = 26912) #convert to UTM Zone 12 Projection
# remove intermediate data
rm(CAMS_no_spatial,sf)
# segment the routes based on segment milepoints
#CAMS_lineref <- ogrlineref(
#  l = CAMS$geometry,
#  mb = CAMS$BEG_MILEPOINT*1609.34,
#  me = CAMS$END_MILEPOINT*1609.34
#)

# write CAMS data to shapefile
CAMS_write <- CAMS %>%
  select(LABEL, SEG_ID, BEG_MILEPOINT, END_MILEPOINT, Seg_Length, SHAPE_Leng) %>%
  group_by(LABEL) %>%
  mutate(BEG_ROUTE = min(BEG_MILEPOINT),
         END_ROUTE = max(END_MILEPOINT),
         BEG_Meters = BEG_MILEPOINT * SHAPE_Leng / (END_ROUTE - BEG_ROUTE),
         END_Meters = END_MILEPOINT * SHAPE_Leng / (END_ROUTE - BEG_ROUTE)) %>%
  unique()
st_write(CAMS_write,"data/shapefile/CAMS.shp")
CAMS_write <- CAMS_write %>% st_drop_geometry()
write_csv(CAMS_write, "data/CAMS_seg")
rm(CAMS_write)

```

```{python Geospatial Segmentation using Arcpy}

# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2022-03-16 21:09:30
"""
import arcpy

def Model():  # Model

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    arcpy.ImportToolbox(r"c:\program files\arcgis\pro\Resources\ArcToolbox\toolboxes\Data Management Tools.tbx")
    # Model Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\samyan\Documents\ArcGIS\Projects\test_CAMS-segmentation\test_CAMS-segmentation.gdb", workspace=r"C:\Users\samyan\Documents\ArcGIS\Projects\test_CAMS-segmentation\test_CAMS-segmentation.gdb"):
        CAMS_routes_CreateRoutes = "CAMS_routes_CreateRoutes"
        CAMS = "C:\\Users\\samyan\\Documents\\ArcGIS\\Projects\\test_CAMS-segmentation\\data\\CAMS.shp"

        # Process: Add Geometry Attributes (Add Geometry Attributes) (management)
        with arcpy.EnvManager(outputCoordinateSystem="PROJCS['NAD_1983_UTM_Zone_12N',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',500000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-111.0],PARAMETER['Scale_Factor',0.9996],PARAMETER['Latitude_Of_Origin',0.0],UNIT['Meter',1.0]]", scratchWorkspace=r"C:\Users\samyan\Documents\ArcGIS\Projects\test_CAMS-segmentation\test_CAMS-segmentation.gdb", workspace=r"C:\Users\samyan\Documents\ArcGIS\Projects\test_CAMS-segmentation\test_CAMS-segmentation.gdb"):
            CAMS_wLength = arcpy.management.AddGeometryAttributes(Input_Features=CAMS, Geometry_Properties=["LENGTH"], Length_Unit="METERS", Area_Unit="", Coordinate_System="PROJCS['NAD_1983_UTM_Zone_12N',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',500000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-111.0],PARAMETER['Scale_Factor',0.9996],PARAMETER['Latitude_Of_Origin',0.0],UNIT['Meter',1.0]]")[0]

        # Process: Calculate Beg (Calculate Field) (management)
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\samyan\Documents\ArcGIS\Projects\test_CAMS-segmentation\test_CAMS-segmentation.gdb", workspace=r"C:\Users\samyan\Documents\ArcGIS\Projects\test_CAMS-segmentation\test_CAMS-segmentation.gdb"):
            CAMS_wBeg = arcpy.management.CalculateField(in_table=CAMS_wLength, field="BEG_Mtr", expression="!BEG_MIL! * !LENGTH! / (!END_ROU! - !BEG_ROU!)", expression_type="PYTHON3", code_block="", field_type="TEXT")[0]

        # Process: Calculate End (Calculate Field) (management)
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\samyan\Documents\ArcGIS\Projects\test_CAMS-segmentation\test_CAMS-segmentation.gdb", workspace=r"C:\Users\samyan\Documents\ArcGIS\Projects\test_CAMS-segmentation\test_CAMS-segmentation.gdb"):
            CAMS_wEnd = arcpy.management.CalculateField(in_table=CAMS_wBeg, field="END_Mtr", expression="!END_MIL! * !LENGTH! / (!END_ROU! - !BEG_ROU!)", expression_type="PYTHON3", code_block="", field_type="TEXT")[0]

        # Process: Make Route Event Layer (Make Route Event Layer) (lr)
        CAMS_Events = "CAMS Events"
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\samyan\Documents\ArcGIS\Projects\test_CAMS-segmentation\test_CAMS-segmentation.gdb", workspace=r"C:\Users\samyan\Documents\ArcGIS\Projects\test_CAMS-segmentation\test_CAMS-segmentation.gdb"):
            arcpy.lr.MakeRouteEventLayer(in_routes=CAMS_routes_CreateRoutes, route_id_field="LABEL", in_table=CAMS_wEnd, in_event_properties="LABEL Line BEG_Mtr END_Mtr", out_layer=CAMS_Events, offset_field="", add_error_field="ERROR_FIELD", add_angle_field="NO_ANGLE_FIELD", angle_type="NORMAL", complement_angle="ANGLE", offset_direction="LEFT", point_event_type="POINT")

if __name__ == '__main__':
    Model()

```
