# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2022-03-16 21:09:30
"""
import arcpy

def Model():  # Model

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    arcpy.ImportToolbox(r"c:\program files\arcgis\pro\Resources\ArcToolbox\toolboxes\Data Management Tools.tbx")
    # Model Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\samyan\Documents\ArcGIS\Projects\test_CAMS-segmentation\test_CAMS-segmentation.gdb", workspace=r"C:\Users\samyan\Documents\ArcGIS\Projects\test_CAMS-segmentation\test_CAMS-segmentation.gdb"):
        CAMS_routes_CreateRoutes = "CAMS_routes_CreateRoutes"
        CAMS = "C:\\Users\\samyan\\Documents\\ArcGIS\\Projects\\test_CAMS-segmentation\\data\\CAMS.shp"

        # Process: Add Geometry Attributes (Add Geometry Attributes) (management)
        with arcpy.EnvManager(outputCoordinateSystem="PROJCS['NAD_1983_UTM_Zone_12N',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',500000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-111.0],PARAMETER['Scale_Factor',0.9996],PARAMETER['Latitude_Of_Origin',0.0],UNIT['Meter',1.0]]", scratchWorkspace=r"C:\Users\samyan\Documents\ArcGIS\Projects\test_CAMS-segmentation\test_CAMS-segmentation.gdb", workspace=r"C:\Users\samyan\Documents\ArcGIS\Projects\test_CAMS-segmentation\test_CAMS-segmentation.gdb"):
            CAMS_wLength = arcpy.management.AddGeometryAttributes(Input_Features=CAMS, Geometry_Properties=["LENGTH"], Length_Unit="METERS", Area_Unit="", Coordinate_System="PROJCS['NAD_1983_UTM_Zone_12N',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',500000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-111.0],PARAMETER['Scale_Factor',0.9996],PARAMETER['Latitude_Of_Origin',0.0],UNIT['Meter',1.0]]")[0]

        # Process: Calculate Beg (Calculate Field) (management)
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\samyan\Documents\ArcGIS\Projects\test_CAMS-segmentation\test_CAMS-segmentation.gdb", workspace=r"C:\Users\samyan\Documents\ArcGIS\Projects\test_CAMS-segmentation\test_CAMS-segmentation.gdb"):
            CAMS_wBeg = arcpy.management.CalculateField(in_table=CAMS_wLength, field="BEG_Mtr", expression="!BEG_MIL! * !LENGTH! / (!END_ROU! - !BEG_ROU!)", expression_type="PYTHON3", code_block="", field_type="TEXT")[0]

        # Process: Calculate End (Calculate Field) (management)
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\samyan\Documents\ArcGIS\Projects\test_CAMS-segmentation\test_CAMS-segmentation.gdb", workspace=r"C:\Users\samyan\Documents\ArcGIS\Projects\test_CAMS-segmentation\test_CAMS-segmentation.gdb"):
            CAMS_wEnd = arcpy.management.CalculateField(in_table=CAMS_wBeg, field="END_Mtr", expression="!END_MIL! * !LENGTH! / (!END_ROU! - !BEG_ROU!)", expression_type="PYTHON3", code_block="", field_type="TEXT")[0]

        # Process: Make Route Event Layer (Make Route Event Layer) (lr)
        CAMS_Events = "CAMS Events"
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\samyan\Documents\ArcGIS\Projects\test_CAMS-segmentation\test_CAMS-segmentation.gdb", workspace=r"C:\Users\samyan\Documents\ArcGIS\Projects\test_CAMS-segmentation\test_CAMS-segmentation.gdb"):
            arcpy.lr.MakeRouteEventLayer(in_routes=CAMS_routes_CreateRoutes, route_id_field="LABEL", in_table=CAMS_wEnd, in_event_properties="LABEL Line BEG_Mtr END_Mtr", out_layer=CAMS_Events, offset_field="", add_error_field="ERROR_FIELD", add_angle_field="NO_ANGLE_FIELD", angle_type="NORMAL", complement_angle="ANGLE", offset_direction="LEFT", point_event_type="POINT")

if __name__ == '__main__':
    Model()
