---
title: "RGUI"
author: "Tomas Barriga"
date: "10/14/2021"
output: html_document
---

```{r setup, include=FALSE}
# INSTALL AND LOAD PACKAGES ################################

# Install pacman ("package manager") if needed
if (!require("pacman")) install.packages("pacman")
# pacman must already be installed; then load contributed
# packages (including pacman) with pacman
pacman::p_load(magrittr, pacman, tidyverse)

source("RGUI_Functions.R")
```

```{r}
location <- read_csv(file.choose(),show_col_types = F)
vehicle <- read_csv(file.choose(),show_col_types = F)
rollups <- read_csv(file.choose(),show_col_types = F)
```

```{r}
location <- check_location(location)
vehicle <- check_vehicle(vehicle)
rollups <- check_rollups(rollups)
```

```{r}
joinprep <- left_join(location,rollups,by='crash_id')
crash <- left_join(joinprep,vehicle,by='crash_id')
crash <- filter_CAMS(crash)
```

```{r}
# write.csv(crash, "C:/Users/barrigat/Downloads/crashtest2.csv",row.names = F)
```

```{r}
aadt <- read_csv(file.choose(),show_col_types = F)
functional_class <- read_csv(file.choose(),show_col_types = F)
intersections <- read_csv(file.choose(),show_col_types = F)
lanes <- read_csv(file.choose(),show_col_types = F)
pavement_messages <- read_csv(file.choose(),show_col_types = F)
speed_limit <- read_csv(file.choose(),show_col_types = F)
urban_code <- read_csv(file.choose(),show_col_types = F)
```

```{r}
aadt <- check_aadt(aadt)
functional_class <- check_functionalclass(functional_class)
intersections <- check_intersections(intersections)
lanes <- check_lanes(lanes)
pavement_messages <- check_pavementmessages(pavement_messages)
speed_limit <- check_speedlimit(speed_limit)
urban_code <- check_urbancode(urban_code)
```

